# Generated by Django 2.0.4 on 2018-04-07 12:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='costs_per_plant',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(help_text='€ per year, including initial costs'), size=10),
        ),
        migrations.AlterField(
            model_name='species',
            name='labour_per_plant',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(help_text='hours per year'), size=10),
        ),
        migrations.AlterField(
            model_name='speciesproduct',
            name='costs_per_plant',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(help_text='€ per year'), size=10),
        ),
        migrations.AlterField(
            model_name='speciesproduct',
            name='labour_per_plant',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(help_text='hours per year'), size=10),
        ),
        migrations.AlterField(
            model_name='speciesproduct',
            name='yield_per_plant',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(help_text='metric tons per year'), size=10),
        ),
    ]
