# Generated by Django 2.0.4 on 2018-04-11 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CultureSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.FloatField(help_text='fraction, monoculture equivalent')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.Culture')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.Species')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='culture',
            name='species',
            field=models.ManyToManyField(through='culture.CultureSpecies', to='species.Species'),
        ),
    ]
